
# Параметр включить(true)/выключить(false) функции плагина
enable: true

# Строка, которая в чате будет заменяться на предмет (будет заменяться, только если игрок имеет разрешение showingitem.use)
matcher: "[item]"

# Строка, на которую будет заменяться строка в параметре "matcher"
# В строке должен обязательно присутсвовать плейсхолдер <%item%>, который будет заменён на предмет
# Для обозначения цветов и декораций использует библиотека net.kyori.adventure. Подробнее: https://docs.advntr.dev/minimessage/format.html
replacement: "<#F08A5D><</#F08A5D><%item%><#F08A5D>></#F08A5D>"
